# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glitter_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glitter_cms.Comment'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glitter_cms.Post'),
        ),
    ]
