# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-14 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glitter_cms', '0002_auto_20180306_1546'),
        ('glitter_cms', '0004_auto_20180313_2255'),
    ]

    operations = [
    ]
